// Code generated by desktop/cmd/gen-bindings; DO NOT EDIT.
//
// 这是 Go 侧 *App 的浏览器可见方法集(desktop/rpc_surface.go 的 allowlist)
// 逐条翻译出来的 TypeScript 契约。改 Go 签名后运行:
//
//   cd desktop && go generate ./...
//
// desktop 的 TestFrontendBindingsAreUpToDate 会在这份文件过期时报错。

import type {
  AccountLoginResult,
  AccountSession,
  BalanceInfo,
  CapabilitiesView,
  CheckpointMeta,
  CommandInfo,
  ContextInfo,
  DirEntry,
  EffortInfo,
  FilePreview,
  FolderListing,
  HardwareBoardFactsView,
  HardwareBoardSummary,
  HardwareDetectView,
  HardwareEvidenceStatusView,
  HardwareInstallStepView,
  HardwareInstallToolchainView,
  HardwareMCPView,
  HardwarePublishInput,
  HardwareRunInput,
  HardwareRunResult,
  HistoryMessage,
  JobView,
  KnowledgeBaseView,
  KnowledgeImportResult,
  KnowledgePromptView,
  KnowledgeSearchResult,
  KnowledgeView,
  MCPServerInput,
  MemoryView,
  Meta,
  ModelInfo,
  NetworkView,
  OTAScaffoldInput,
  OTAScaffoldResult,
  PendingPrompts,
  ProviderView,
  QuestionAnswer,
  ReferenceFileResult,
  SerialResult,
  SessionMeta,
  SettingsView,
  SlashArgsResult,
  TabMeta,
  UpdateInfo,
  WorkspaceMeta,
} from "./types";

// AppBindings 是三种壳(Wails 绑定 / Web 模式的 POST /rpc/<方法名> / 裸浏览器 mock)
// 共同实现的接口,组件代码因此完全不知道自己跑在哪种壳里。
export interface AppBindings {
  // AccountLogin 校验账号密码,成功则持久化会话。
  AccountLogin(account: string, password: string): Promise<AccountLoginResult>;

  // AccountLogout 清除会话,并把 AI 切回直连(清网关 env + 重建 controller)。
  AccountLogout(): Promise<void>;

  // AccountSessionInfo 返回当前会话(未登录则 LoggedIn=false)。token 不外泄。
  // PlatformMode 由 defer 按当前模式统一盖章(覆盖所有 return 路径,不会漏某条):前端据此决定
  // 未登录时是否弹登录门。
  AccountSessionInfo(): Promise<AccountSession>;

  // AddHardwareMCPServer 把本机的硬件 MCP 二进制登记成一台服务器。
  AddHardwareMCPServer(): Promise<number>;

  // AddMCPServer 把一台 MCP 服务器写进配置,返回配置里现有服务器总数。
  AddMCPServer(in_: MCPServerInput): Promise<number>;

  // AddPermissionRule appends a rule to the allow/ask/deny list.
  AddPermissionRule(list: string, rule: string): Promise<void>;

  // AddSkillPath adds a custom skill root to the user config and rebuilds the
  // controller so the skills index and slash menu reflect it immediately.
  AddSkillPath(path: string): Promise<void>;

  // AnswerQuestion resolves a pending ask_request (the `ask` tool) by ID with the
  // user's selections per question. tabID 指定事件来源标签(A2)。
  AnswerQuestion(tabId: string, id: string, answers: QuestionAnswer[]): Promise<void>;

  // ApplyUpdate downloads, verifies, installs the latest build, then relaunches. On
  // macOS it can't self-update (unsigned bundle), so it defers to the download page.
  // Progress is streamed on the "updater:progress" event; on success the process exits.
  ApplyUpdate(): Promise<void>;

  // Approve answers a pending approval_request by ID: allow runs the call, session
  // also remembers the grant for the rest of the session. tabID 指定事件来源标签——
  // 后台标签的审批必须打到它自己的 controller,而不是当前活动标签(A2)。
  Approve(tabId: string, id: string, allow: boolean, session: boolean): Promise<void>;

  // AttachmentDataURL 把一个附件读成 data URL,供前端内联预览。
  AttachmentDataURL(path: string): Promise<string>;

  // Balance queries the active provider's wallet balance (a network call). It
  // returns an empty (unavailable) readout when no provider balance_url is set, the
  // controller is down, or the fetch fails — so the status bar simply shows nothing
  // rather than an error.
  Balance(): Promise<BalanceInfo>;

  // BrowseDir 列出一个目录,供「选择文件夹」这类浏览界面用。
  BrowseDir(path: string): Promise<FolderListing>;

  // Cancel aborts the in-flight turn.
  Cancel(): Promise<void>;

  // Capabilities projects the session's MCP servers (connected + failed) and skills
  // for the MCP & Skills drawer. Non-nil slices so the frontend can map over them.
  //
  // 这是一处纯 DTO 组装:服务器那半来自 mcpService,技能那半来自活动标签的 controller
  // 与当前项目的技能根 —— App 只负责把两半拼成前端要的一个视图。
  Capabilities(): Promise<CapabilitiesView>;

  // CheckUpdate is intentionally disabled in this fork (onecreat). It is distributed
  // manually and has no own update channel yet, so it must NOT phone home to the upstream
  // reasonix endpoints in updater.go — doing so leaks usage and could steer users into
  // installing upstream over this fork. Returns "no update" with zero network calls, so
  // the frontend's UpdateBanner stays hidden. To re-enable later: restore the
  // fetchManifest/evaluate path below and repoint the endpoints to onecreat's channel.
  CheckUpdate(): Promise<UpdateInfo | null>;

  // Checkpoints lists the session's rewind points, oldest first, for the rewind UI.
  Checkpoints(): Promise<CheckpointMeta[]>;

  // CloseTab 关闭一个标签:从注册表移除,快照并关掉它的 controller;若关的是活动标签,
  // 自动切到末尾的另一个标签。
  CloseTab(id: string): Promise<void>;

  // Commands lists the slash commands available this session — built-in actions,
  // custom commands (.reasonix/commands), and MCP prompts — for the composer's "/"
  // autocomplete menu.
  Commands(): Promise<CommandInfo[]>;

  // Compact runs one compaction pass on demand.
  // Compact runs a plain compaction pass (the "compact now" button). Focus-guided
  // compaction goes through Submit("/compact <focus>") instead.
  Compact(): Promise<void>;

  // ContextUsage returns the latest context-window gauge numbers.
  ContextUsage(): Promise<ContextInfo>;

  // CreateTab 新建一个独立任务标签并设为活动;controller 异步装配(期间 Ready=false,
  // 前端显示 loading),装配完发 agent:ready:<id>。后台标签照常在自己的 goroutine 里
  // 跑、事件发到自己的通道,所以多个标签可真并行(像 Codex / Claude Code 的多任务)。
  CreateTab(kind: string): Promise<TabMeta>;

  // DeleteProvider removes a provider (refused for the current default_model).
  DeleteProvider(name: string): Promise<void>;

  // DeleteSession 删除一个历史会话文件。
  DeleteSession(path: string): Promise<void>;

  Effort(): Promise<EffortInfo>;

  // Forget 删掉一条已记住的事实。
  Forget(name: string): Promise<void>;

  // Fork branches the conversation at the start of turn into a new session
  // (preserving the current one), keeping code intact, and switches to the branch.
  // The frontend re-reads History after this resolves.
  Fork(turn: number): Promise<void>;

  // HardwareBoardFacts 返回某块板卡的引脚 / 电平 / 平台 API 事实卡。
  HardwareBoardFacts(board: string, platform: string): Promise<HardwareBoardFactsView>;

  // HardwareBoardList 返回注册表里的全部板卡,供面板下拉使用。
  HardwareBoardList(): Promise<HardwareBoardSummary[]>;

  // HardwareDetect 探测当前项目的工具链 / 板卡 / 设备。
  HardwareDetect(): Promise<HardwareDetectView>;

  // HardwareEvidenceExport 把证据链导出成 Markdown,返回文件路径。
  HardwareEvidenceExport(projectDir: string): Promise<string>;

  // HardwareEvidenceStatus 汇报当前项目的证据链完成度。
  HardwareEvidenceStatus(): Promise<HardwareEvidenceStatusView>;

  // HardwareInstallArduinoCLI 只装 arduino-cli 本体。
  HardwareInstallArduinoCLI(): Promise<HardwareInstallStepView>;

  // HardwareInstallCore 只装一个板卡 core。
  HardwareInstallCore(core: string): Promise<HardwareInstallStepView>;

  // HardwareInstallToolchain 安装 arduino-cli 与指定的板卡 core。
  HardwareInstallToolchain(cores: string[]): Promise<HardwareInstallToolchainView>;

  // HardwareMCP 报告本机硬件 MCP 二进制的可用与接入状态。
  HardwareMCP(): Promise<HardwareMCPView>;

  // HardwareMonitor 采一段串口输出作为证据。
  HardwareMonitor(input: HardwareRunInput): Promise<HardwareRunResult>;

  // HardwareOTAUpload 走 WiFi 的 OTA 烧录。
  HardwareOTAUpload(input: HardwareRunInput): Promise<HardwareRunResult>;

  // HardwarePublishFirmware 发布固件到远端。
  HardwarePublishFirmware(input: HardwarePublishInput): Promise<HardwareRunResult>;

  // HardwareScaffoldOTA 生成一个含 OTA 底座的项目目录:<dest>/<name>/<name>.ino。
  HardwareScaffoldOTA(input: OTAScaffoldInput): Promise<OTAScaffoldResult>;

  // HardwareUpload 烧录到板卡。
  HardwareUpload(input: HardwareRunInput): Promise<HardwareRunResult>;

  // HardwareValidate 编译校验当前项目。
  HardwareValidate(input: HardwareRunInput): Promise<HardwareRunResult>;

  // History 返回活动标签当前会话的消息记录。
  History(): Promise<HistoryMessage[]>;

  // ImportReferenceFile reads `pathOrURL` and returns its extracted text so the
  // student can paste study material (Word/PDF/HTML/Markdown/code) into Composer
  // as one "pasted block". Accepts:
  //
  //   - http(s):// URL  → fetch + HTML strip
  //   - local file path → extension-dispatched parser
  //
  // Note: PDF/DOC/DOCX/RTF use macOS system tools (textutil / pdftotext) so we
  // avoid adding heavy Go deps. Linux/Windows fall back to "tell the user to
  // convert" until those binaries are bundled.
  ImportReferenceFile(pathOrURL: string): Promise<ReferenceFileResult>;

  // Jobs returns the still-running background jobs for the status bar. It refreshes
  // on demand (mount, turn end, and on each notice the frontend receives).
  Jobs(): Promise<JobView[]>;

  // KnowledgeBuildPrompt creates the augmented user prompt for Mode A. Documents
  // stay local; only the top matching snippets are included in this one model call.
  KnowledgeBuildPrompt(baseIDs: string[], question: string, limit: number): Promise<KnowledgePromptView>;

  KnowledgeCreate(name: string): Promise<KnowledgeBaseView>;

  KnowledgeDelete(id: string): Promise<void>;

  // KnowledgeImportFiles opens a native file picker and imports selected local
  // text/code files into one knowledge base.
  KnowledgeImportFiles(baseId: string): Promise<KnowledgeImportResult>;

  // KnowledgeImportPaths 按绝对路径导入知识库文件(不弹原生对话框)。Web 模式下前端先把
  // 浏览器选的文件 POST /upload 落到临时目录,拿到路径后调这里;桌面版仍走 KnowledgeImportFiles。
  KnowledgeImportPaths(baseId: string, paths: string[]): Promise<KnowledgeImportResult>;

  KnowledgeSearch(baseIDs: string[], query: string, limit: number): Promise<KnowledgeSearchResult>;

  // KnowledgeView returns the local Mode A knowledge-base snapshot. It does not
  // read project memory or any workspace files automatically; only explicitly
  // imported files appear here.
  KnowledgeView(): Promise<KnowledgeView>;

  // ListDir 列出项目内某个相对目录,供 @ 引用菜单用。
  ListDir(rel: string): Promise<DirEntry[]>;

  // ListSessions 列出历史会话。
  ListSessions(): Promise<SessionMeta[]>;

  // ListTabs 返回所有标签快照(按打开顺序),供前端渲染标签栏。
  ListTabs(): Promise<TabMeta[]>;

  // ListWorkspaces 列出最近打开过的项目文件夹。
  ListWorkspaces(): Promise<WorkspaceMeta[]>;

  // MarkSessionKind 给当前会话打上类型标记(chat / 任务等)。
  MarkSessionKind(kind: string): Promise<void>;

  // Memory 返回记忆文档与事实的视图。
  Memory(): Promise<MemoryView>;

  // Meta reports the model label, readiness, any startup error, the working
  // directory (for the status line), and the runtime event channel the frontend
  // subscribes to. Bypass/PlanMode/Running 读自活动标签 controller 的真实状态——切回
  // 标签时前端据此恢复 pill 与 spinner,而不是凭全局 UI 态猜测(A3/A8)。
  Meta(): Promise<Meta>;

  // Models flattens the configured providers into their (provider, model) pairs —
  // the switcher's options — marking the active one. A vendor with a `models` list
  // yields one entry per model, all sharing the same endpoint/key. Unconfigured
  // providers are skipped. Result is non-nil: the frontend reads .length, so a nil
  // slice (JSON null) would crash the switcher on an empty list.
  Models(): Promise<ModelInfo[]>;

  // NewSession snapshots the current conversation and rotates to a fresh one.
  NewSession(): Promise<void>;

  // OpenDownloadPage opens the releases page in the browser — the macOS manual-update
  // path and a fallback link elsewhere.
  OpenDownloadPage(): Promise<void>;

  // OpenFolder 用文件管理器打开一个绝对路径。
  OpenFolder(path: string): Promise<void>;

  // OpenWorkspacePath 用系统默认程序打开项目内的一个路径。
  OpenWorkspacePath(rel: string): Promise<void>;

  PendingPrompts(tabId: string): Promise<PendingPrompts>;

  // PickReferenceFile pops the OS file picker so the student can choose a Word /
  // PDF / HTML / Markdown / code file to attach as reference material. Returns the
  // absolute path; empty string when the user cancels.
  PickReferenceFile(): Promise<string>;

  // PickSkillFolder opens a directory picker for adding custom skill roots. It only
  // returns a path; AddSkillPath performs normalization and writes config.
  PickSkillFolder(): Promise<string>;

  // PickWorkspace 弹出原生文件夹选择框。
  PickWorkspace(): Promise<string>;

  // PreviewSession 只读地预览一个历史会话的消息记录。
  PreviewSession(path: string): Promise<HistoryMessage[]>;

  // shutdown snapshots the conversation and stops plugin subprocesses on close.
  // 遍历所有标签(不只活动镜像):多标签并行时,后台标签进行中的最后一轮也要落盘,
  // 它们的 MCP stdio 子进程也要关闭,否则退出/自更新会丢数据 + 留孤儿子进程(A7)。
  // Quit 请求优雅退出整个程序。前端「退出 OneCreat」按钮调它(Web 模式);桌面版按钮隐藏,
  // 但方法照常可用。真正的关闭动作交给宿主外壳:Wails 关窗触发 OnShutdown;Web 通知运行
  // 循环走 app.shutdown + 停服。这里不直接 shutdown,好让本次 RPC 先把 200 回给浏览器。
  Quit(): Promise<void>;

  // ReadFile 读一个项目内文件的有界预览。
  ReadFile(rel: string): Promise<FilePreview>;

  // RefreshAccountSession 向平台 /api/onecreat/session 拉最新 points/tiers(每轮对话结束后调,
  // 让余额实时下降、看得到消耗)。网络问题或 token 失效则保持本地快照不变(AI 调用自己会报
  // 401 提示重登)。不重建 controller,纯刷新展示数据。
  RefreshAccountSession(): Promise<AccountSession>;

  // RefreshSkills rebuilds the controller without changing config, reloading skill
  // discovery, the system prompt index, and slash completions.
  RefreshSkills(): Promise<void>;

  // Remember 往指定作用域写一条事实。
  Remember(scope: string, note: string): Promise<string>;

  // RemoveMCPServer 从配置里删掉一台服务器。
  RemoveMCPServer(name: string): Promise<void>;

  // RemovePermissionRule drops a rule from the allow/ask/deny list.
  RemovePermissionRule(list: string, rule: string): Promise<void>;

  // RemoveSkillPath removes a custom skill root from the user config and rebuilds.
  RemoveSkillPath(path: string): Promise<void>;

  // RenameSession 给一个历史会话改标题。
  RenameSession(path: string, title: string): Promise<void>;

  // ResumeSession 把一个历史会话装回活动标签,返回它的消息记录。
  ResumeSession(path: string): Promise<HistoryMessage[]>;

  // RetryMCPServer 重连一台失败的服务器。
  RetryMCPServer(name: string): Promise<void>;

  // RevealWorkspacePath 在文件管理器里选中项目内的一个路径。
  RevealWorkspacePath(rel: string): Promise<void>;

  // Rewind restores the session to the start of turn. scope is "code",
  // "conversation", or "both" (anything else is treated as "both"). The frontend
  // re-reads History after this resolves.
  Rewind(turn: number, scope: string): Promise<void>;

  // SanitizeProjectName 把项目名归一成烤进板子 / 发布落盘用的名字(复用脚手架/发布同一实现)。
  // 前端拿它比对"新建名"与"发布名" sanitize 后是否一致,避免自行重实现一份 sanitize(H1)。
  SanitizeProjectName(name: string): Promise<string>;

  // SaveDoc 直接保存整篇记忆文档。
  SaveDoc(path: string, body: string): Promise<string>;

  // SavePastedFile 把粘贴/拖入的附件落盘,返回可引用的路径。
  SavePastedFile(name: string, dataURL: string): Promise<string>;

  // SavePastedImage 把粘贴进来的图片落盘,返回可引用的路径。
  SavePastedImage(dataURL: string): Promise<string>;

  // SaveProvider adds or updates a provider. A single model fills `model`; several
  // fill `models` (with `default`). The shared key/endpoint live on the entry.
  SaveProvider(p: ProviderView): Promise<void>;

  // SerialClose 关闭当前串口连接(幂等)。
  SerialClose(): Promise<void>;

  // SerialOpen 按指定波特率打开串口并开始持续读。
  SerialOpen(portName: string, baud: number): Promise<SerialResult>;

  // SerialPorts 列出可用串口(给面板下拉)。
  SerialPorts(): Promise<string[]>;

  // SerialWrite 往当前串口写一段数据。
  SerialWrite(data: string): Promise<SerialResult>;

  // SetActiveTab 把「活动标签」指向目标标签:不带 tabID 的既有会话类方法随之作用到
  // 该标签。前端在切换标签、以及对某标签发指令前调用它。未知 id 是空操作。
  //
  // 切换只改一个 id —— 没有 controller / sink / model 需要跟着重指,所以也就不存在
  // 「漏同步某个镜像字段」这类 bug。
  SetActiveTab(id: string): Promise<void>;

  // SetAgentParams updates sampling temperature, the optional max-steps guard, and
  // the base system prompt.
  SetAgentParams(temperature: number, maxSteps: number, systemPrompt: string): Promise<void>;

  // SetBypass toggles YOLO mode for the session: auto-approve every tool call
  // (writers and bash run without asking). Deny rules still apply. Runtime-only —
  // not written to config, so it resets on relaunch.
  SetBypass(tabId: string, on: boolean): Promise<void>;

  // SetCoachMode 设置某标签的「协作模式」persona(空串=默认无 persona)。preamble 随每个
  // turn 注入(见 Compose),按 tabID 路由并记录 want 状态(A8)。
  SetCoachMode(tabId: string, preamble: string): Promise<void>;

  // SetDefaultModel sets the config default and switches the live model to it.
  SetDefaultModel(ref: string): Promise<void>;

  SetEffort(level: string): Promise<void>;

  // SetMCPServerEnabled 在本会话里开关一台服务器。
  SetMCPServerEnabled(name: string, enabled: boolean): Promise<void>;

  // SetModel 换掉活动标签的模型并带过历史。
  SetModel(name: string): Promise<void>;

  // SetNetwork updates ordinary outbound proxy settings.
  SetNetwork(n: NetworkView): Promise<void>;

  // SetOnecreatTier 切换当前档位(1/2/3):写回 session.json + 刷新网关 env + 重建 controller,
  // 让下一条消息按新档位走。背后是什么模型客户端不知道(平台映射)。
  SetOnecreatTier(index: number): Promise<void>;

  // SetPermissionMode sets the writer-fallback mode (ask|allow|deny).
  SetPermissionMode(mode: string): Promise<void>;

  // SetPlanMode toggles read-only plan mode for one tab. 记录到标签的 want 状态(即使
  // controller 还在异步装配也不丢),并施加到已就绪的 controller——避免「pill 显示只读、
  // 实际可写」的安全错觉(A8)。
  SetPlanMode(tabId: string, on: boolean): Promise<void>;

  // SetPlannerModel sets (or, with "", clears) the two-model planner.
  SetPlannerModel(ref: string): Promise<void>;

  // SetProviderKey writes a secret to ./.env under the given env-var name (the one a
  // provider's api_key_env points at) and rebuilds so it resolves immediately.
  SetProviderKey(apiKeyEnv: string, value: string): Promise<void>;

  // SetSandbox updates the bash sandbox mode, network egress, and write roots.
  SetSandbox(bash: string, network: boolean, workspaceRoot: string, allowWrite: string[]): Promise<void>;

  // Settings returns the current configuration for the Settings panel.
  Settings(): Promise<SettingsView>;

  // SlashArgs completes the arguments of a management slash command (/mcp, /model,
  // /skill, /hooks) for the composer — the same logic the chat TUI uses. Empty
  // Items means the input has no structured arguments to complete.
  SlashArgs(input: string): Promise<SlashArgsResult>;

  // Submit runs raw user input as a turn; slash commands and @-references are
  // resolved by the controller. Output arrives asynchronously on eventChannel.
  Submit(input: string): Promise<void>;

  // SubmitDisplay runs input as a turn while recording a shorter UI-only display
  // string for the saved desktop transcript. The model still receives input.
  SubmitDisplay(display: string, input: string): Promise<void>;

  // SummarizeFrom / SummarizeUpTo compress the conversation from / up to the start
  // of turn into one summary (Claude Code's "summarize from/up to here"), keeping
  // code intact. The frontend re-reads History after this resolves.
  SummarizeFrom(turn: number): Promise<void>;

  SummarizeUpTo(turn: number): Promise<void>;

  // SwitchWorkspace 把活动标签切到另一个项目文件夹。
  SwitchWorkspace(dir: string): Promise<string>;

  // Version returns the build version injected via -ldflags (see main.go). The
  // frontend displays it; CheckUpdate compares against it.
  Version(): Promise<string>;
}
