package main

//go:generate go run ./cmd/gen-bindings .

// rpcPublicMethods is the browser-visible application API.
//
// This is deliberately an allowlist, not "all exported methods minus a few". Adding
// an exported Go method must not silently turn it into an HTTP endpoint.
//
// It is also the *input* to the frontend contract: desktop/cmd/gen-bindings reads
// this list plus the listed methods' Go signatures and writes
// frontend/src/lib/bindings.generated.ts, the AppBindings interface all three
// shells implement. So growing the contract is one edit here plus
// `go generate ./...` — the 120-method TypeScript interface is no longer
// maintained by hand, and a changed signature can no longer drift past a test
// that only compared names. TestFrontendBindingsAreUpToDate fails on a stale file.
var rpcPublicMethods = map[string]struct{}{
	"Submit":                    {},
	"SubmitDisplay":             {},
	"Cancel":                    {},
	"Approve":                   {},
	"AnswerQuestion":            {},
	"PendingPrompts":            {},
	"SetPlanMode":               {},
	"SetCoachMode":              {},
	"Compact":                   {},
	"NewSession":                {},
	"CreateTab":                 {},
	"CloseTab":                  {},
	"ListTabs":                  {},
	"SetActiveTab":              {},
	"History":                   {},
	"Checkpoints":               {},
	"Rewind":                    {},
	"Fork":                      {},
	"SummarizeFrom":             {},
	"SummarizeUpTo":             {},
	"ListSessions":              {},
	"ResumeSession":             {},
	"PreviewSession":            {},
	"DeleteSession":             {},
	"RenameSession":             {},
	"MarkSessionKind":           {},
	"ListWorkspaces":            {},
	"PickWorkspace":             {},
	"SwitchWorkspace":           {},
	"BrowseDir":                 {},
	"AccountLogin":              {},
	"AccountLogout":             {},
	"AccountSessionInfo":        {},
	"SetOnecreatTier":           {},
	"RefreshAccountSession":     {},
	"ContextUsage":              {},
	"Balance":                   {},
	"Jobs":                      {},
	"Meta":                      {},
	"Commands":                  {},
	"Capabilities":              {},
	"AddMCPServer":              {},
	"HardwareMCP":               {},
	"HardwareBoardList":         {},
	"HardwareDetect":            {},
	"HardwareInstallToolchain":  {},
	"HardwareInstallArduinoCLI": {},
	"HardwareInstallCore":       {},
	"HardwareEvidenceStatus":    {},
	"HardwareEvidenceExport":    {},
	"HardwareBoardFacts":        {},
	"PickReferenceFile":         {},
	"ImportReferenceFile":       {},
	"HardwareValidate":          {},
	"HardwareUpload":            {},
	"HardwareMonitor":           {},
	"HardwareOTAUpload":         {},
	"HardwarePublishFirmware":   {},
	"HardwareScaffoldOTA":       {},
	"SanitizeProjectName":       {},
	"SerialPorts":               {},
	"SerialOpen":                {},
	"SerialClose":               {},
	"SerialWrite":               {},
	"AddHardwareMCPServer":      {},
	"KnowledgeView":             {},
	"KnowledgeCreate":           {},
	"KnowledgeDelete":           {},
	"KnowledgeImportFiles":      {},
	"KnowledgeImportPaths":      {},
	"KnowledgeSearch":           {},
	"KnowledgeBuildPrompt":      {},
	"RemoveMCPServer":           {},
	"RetryMCPServer":            {},
	"PickSkillFolder":           {},
	"AddSkillPath":              {},
	"RemoveSkillPath":           {},
	"RefreshSkills":             {},
	"SetMCPServerEnabled":       {},
	"SlashArgs":                 {},
	"ListDir":                   {},
	"ReadFile":                  {},
	"OpenWorkspacePath":         {},
	"RevealWorkspacePath":       {},
	"OpenFolder":                {},
	"SavePastedImage":           {},
	"SavePastedFile":            {},
	"AttachmentDataURL":         {},
	"Models":                    {},
	"SetModel":                  {},
	"Effort":                    {},
	"SetEffort":                 {},
	"Memory":                    {},
	"Remember":                  {},
	"Forget":                    {},
	"SaveDoc":                   {},
	"Settings":                  {},
	"SetDefaultModel":           {},
	"SetPlannerModel":           {},
	"SaveProvider":              {},
	"DeleteProvider":            {},
	"SetProviderKey":            {},
	"SetPermissionMode":         {},
	"AddPermissionRule":         {},
	"RemovePermissionRule":      {},
	"SetSandbox":                {},
	"SetNetwork":                {},
	"SetAgentParams":            {},
	"SetBypass":                 {},
	"Version":                   {},
	"CheckUpdate":               {},
	"ApplyUpdate":               {},
	"OpenDownloadPage":          {},
	"Quit":                      {},
}
